<?php

/**
 * @file 
 */

/**
 * Implementation of hook_form_alter().
 */
function uc_pricequote_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'uc_quote_admin_settings') {
    $form['uc_pricequote'] = array(
      '#type' => 'fieldset',
      '#title' => t('Shipping Quote Pane Cart Display'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
	  '#weight' => '0',
    );
    $form['uc_pricequote']['uc_pricequote_default'] = array(
      '#type' => 'textfield',
      '#title' => t('Default price quote'),
      '#default_value' => variable_get('uc_pricequote_default', 0),
      '#description' => t('If the cart contents is greater than or equal to the specified value Shipping Pane will not display.'),
    );
    $form['#submit'][] = 'uc_pricequote_admin_settings_submit';

  }

}

/**
 * Submitting uc_quote_admin_settings
 */
function uc_pricequote_admin_settings_submit ($form, &$form_state) {
  variable_set('uc_pricequote_default', $form_state['values']['uc_pricequote_default']);
}

/**
 * Controlling price for shipping quote pane
 */
function uc_pricequote_cart_pane_alter(&$panes, $items) {
  foreach ($panes as $key=>$pane) {
    if ($pane['id'] == 'quotes') {
      $cart_contents = uc_cart_get_contents();
      $total = 0;
      foreach ($cart_contents as $content) {
        $total = $total +  $content->qty * $content->price;
      }
      if ($total >= variable_get('uc_pricequote_default', 0)) {
        $panes[$key]['body'] = '<div class="order-free-shipping">'. t('Your order qualifies for free shipping.') .'</div>'; // Set the body to a new value
      }
    }
  }
}